import { COLORS } from "./constants";

export const styles = {
  wrap: {
    fontFamily: "'IBM Plex Mono', 'Courier New', monospace",
    maxWidth: 780,
    margin: "0 auto",
    padding: "1.5rem",
    color: "#e8e6e1",
    background: "transparent",
    border: "none",
    borderRadius: 0,
    fontSize: 13,
  },
  header: { marginBottom: "1.25rem" },
  h1: { fontSize: 18, fontWeight: 500, margin: 0, letterSpacing: "-0.02em", color: "#f0ede8" },
  subtitle: { fontSize: 12, color: "#888780", marginTop: 3, fontFamily: "sans-serif" },
  statusRow: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    marginTop: 8,
    fontSize: 12,
    color: "#888780",
    fontFamily: "sans-serif",
  },
  sep: { border: "none", borderTop: "0.5px solid rgba(136,135,128,0.2)", margin: "1.25rem 0" },
  formGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10, marginBottom: "1rem" },
  field: { display: "flex", flexDirection: "column", gap: 5 },
  label: {
    fontSize: 10,
    color: "#888780",
    letterSpacing: "0.07em",
    textTransform: "uppercase",
    fontFamily: "sans-serif",
  },
  input: {
    background: "rgba(255,255,255,0.04)",
    border: "0.5px solid rgba(136,135,128,0.3)",
    borderRadius: 6,
    padding: "7px 10px",
    fontSize: 13,
    color: "#e8e6e1",
    fontFamily: "'IBM Plex Mono', monospace",
    outline: "none",
    width: "100%",
    boxSizing: "border-box",
  },
  btnRow: { display: "flex", gap: 8 },
  simLine: {
    marginTop: 10,
    padding: "7px 10px",
    fontSize: 11,
    color: "#888780",
    border: "0.5px solid rgba(136,135,128,0.2)",
    borderRadius: 6,
    background: "rgba(255,255,255,0.02)",
    fontFamily: "sans-serif",
    letterSpacing: "0.01em",
  },
  btnStart: {
    flex: 1,
    padding: "10px 0",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    border: "0.5px solid rgba(136,135,128,0.4)",
    borderRadius: 6,
    background: "rgba(255,255,255,0.06)",
    color: "#f0ede8",
    fontFamily: "sans-serif",
    letterSpacing: "0.01em",
    transition: "background 0.15s",
  },
  btnStop: {
    flex: 1,
    padding: "10px 0",
    fontSize: 13,
    fontWeight: 500,
    cursor: "pointer",
    border: "0.5px solid rgba(226,75,74,0.5)",
    borderRadius: 6,
    background: "rgba(226,75,74,0.5)",
    color: "#f0ede8",
    fontFamily: "sans-serif",
    letterSpacing: "0.01em",
    transition: "background 0.15s",
  },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(4, minmax(0, 1fr))", gap: 9, margin: "1.25rem 0" },
  statCard: {
    background: "rgba(255,255,255,0.04)",
    border: "0.5px solid rgba(136,135,128,0.15)",
    borderRadius: 8,
    padding: "11px 13px",
  },
  statLabel: {
    fontSize: 10,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "#888780",
    marginBottom: 5,
    fontFamily: "sans-serif",
  },
  statValue: { fontSize: 24, fontWeight: 500, color: "#f0ede8" },
  chartCard: {
    border: "0.5px solid rgba(136,135,128,0.2)",
    borderRadius: 12,
    padding: "1rem 1.25rem",
    background: "rgba(255,255,255,0.02)",
  },
  chartTop: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 12 },
  chartLbl: {
    fontSize: 11,
    color: "#888780",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    fontFamily: "sans-serif",
  },
  legend: { display: "flex", gap: 14 },
  legItem: { display: "flex", alignItems: "center", gap: 5, fontSize: 11, color: "#888780", fontFamily: "sans-serif" },
  footerBar: { display: "flex", justifyContent: "space-between", marginTop: 8 },
  footerTxt: { fontSize: 10, color: "#5f5e5a", letterSpacing: "0.03em" },
};
